# 'muid': '11111111'
# 'first_name': 'Jim',
# 'middle_initial': 'A',
# 'last_name': 'Smithtest',
# 'date_of_birth': '12/30/1982',
# 'personal_email': 'williams_ma@mercer.edu', 'campus': 'Macon',
# 'building': 'Tarver',
# 'office_or_room_number': 'Help Desk Office',
# 'employee_title': 'Help Desk Technician',
# 'department': 'Client Support Services',
# 'supervisor': 'Brent Walker',
# 'start_date': '6/15/2018',

# 'needs_telephone_service': 'Yes', 'using_existing_ext': 'Yes',
# 'existing_telephone_number': '2240',
# 'account_number': '1345123',
# 'display_name': 'Jim Smithtest',
# 'long_distance_code': 'on',
# 'international_calling': 'on',
# 'voice_mail': 'on',
# 'call_forwarding': 'on',

'email_account': 'on',
# 'mymercer': 'on',
# 'campusvue_finance': 'on',
# 'CampusNexus_student': 'on',
'existing_nexus_user': 'Yes',
# 'CampusNexus_student_user_to_copy': 'Mark Williams',
'nexus_requirements': 'blank',
# 'shared_folder_access': 'on',
# 'name_of_the_share': '\\merceru.local\\it-software',
# 'vpn': 'on',
# '25live_access': 'on',

# 'computer_status': 'Using existing',
# 'existing_computer_RT_number': 'RT1805123',
'previous_vdi_user': 'blank',
'H2_4': 'Miscellaneous Information',
'additional_notes': 'This is not a real employee ticket. Just a form submission with maximum number of fields filled out as a test.'
